### ISSUE TITLE
cookiecutter

### ISSUE THREAD

**Issue by uweschmitt** [manparvesh/click-boilerplate#1]
Hi,
did you consider to implement your project scaffold as a cookiecutter template ? Would give you more flexibility and manual manipulation of names compared to just cloning your project.

Best
Uwe

**Comment by manparvesh** [comment]
@uweschmitt thanks for the suggestion.

I wasn't aware of `cookiecutter` when I write this, but someone on reddit suggested me to check it out and I found out that it can be very helpful. Creating a cookiecutter template is definitely on the TODO list of this project!

I appreciate you taking your time to give feedback.
